language: rust
dist: xenial
rust:
  - nightly-2019-06-18
cache:
  - cargo
  - yarn
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - REDIS_URL=redis://127.0.0.1/
    - RUST_TEST_THREADS=1
    - DATABASE_URL=postgres://postgres@127.0.0.1:5432/test_db
services:
  - redis-server
  - postgresql
  - docker
before_script:
  - cargo install diesel_cli --no-default-features --features postgres || echo "already installed"
  - diesel database setup
script:
  - cargo test --all
  - make build_server
  - make build_client
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make docker_release_pr; fi'
