[workspace]

members = [
    "octo-budget-api",
    "octo-budget-api-server",
    "octo-budget-lib",
    "octo-budget-frontend",
    "middlewares",
    "db_seed",
    "models",
    "octo-budget-shared",
]
