version: "3.7"
services:
  db:
    image: "postgres:alpine"
    command: "-c 'max_connections=200'"
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_USER: "rustapp"
      POSTGRES_DB: "octo-budget-api"
    ports:
      - 5432
volumes:
  pg_data:
