[package]
name = "octo-budget-lib"
version = "0.1.0"
authors = ["Aliaksandr Rahalevich <saksmlz@gmail.com>"]
edition = "2018"

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
jsonwebtoken = "6"
time = "0.1"
failure = "0.1"
actix-web = "2.0"
actix-http = "*"
futures = "*"
log = "0.4"
