[package]
name = "octo-budget-lib"
version = "0.1.0"
authors = ["Aliaksandr Rahalevich <saksmlz@gmail.com>"]

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
jsonwebtoken = "5"
time = "0.1"
failure = "0.1"
