[package]
name = "octo-budget-api"
version = "0.1.0"
authors = ["Aliaksandr Rahalevich <saksmlz@gmail.com>"]

[dependencies]
octo-budget-lib = { path = "../octo-budget-lib" }
actix-web = "0.7"
actix = "*"
env_logger = "0.5"
serde_json = { version = "1.0" }
failure = "0.1"
failure_derive = "0.1"
diesel = { version = "1.3", features = ["numeric", "chrono", "postgres", "r2d2"] }
dotenv = "0.13"
djangohashers = { version = "0.3", features = ["fpbkdf2"] }
r2d2 = "0.8"
serde = "*"
serde_derive = "*"
futures = "0.1"
lazy_static = "1.1"
bytes = "*"
chrono = { version = "*", features = ["serde"] }
bigdecimal = "0.0.11" # must match version of diesel dependency
