[package]
authors = ["Aliaksandr Rahalevich <saksmlz@gmail.com>"]
edition = "2018"
name = "octo-budget-api"
version = "0.1.0"

[dependencies]
actix = "*"
actix-web = "0.7"
actix-redis = "*"
bytes = "*"
dotenv = "0.13"
env_logger = "0.6"
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
lazy_static = "1.1"
r2d2 = "0.8"
redis-async = "*"
serde = "*"
serde_derive = "*"
url = "*"
tokio = "*"
tokio-async-await = "*"

[dependencies.bigdecimal]
version = "0.0.14" # must match version of diesel dependency
features = ["serde"]

[dependencies.actix-web-async-await]
git = "https://github.com/saks/actix-web-async-await"

[dependencies.chrono]
features = ["serde"]
version = "*"

[dependencies.diesel]
features = ["numeric", "chrono", "postgres", "r2d2"]
version = "1.3"

[dependencies.djangohashers]
features = ["fpbkdf2"]
version = "1"

[dependencies.octo-budget-lib]
path = "../octo-budget-lib"

[dependencies.serde_json]
version = "1.0"
