[package]
authors = ["Aliaksandr Rahalevich <saksmlz@gmail.com>"]
edition = "2018"
name = "octo-budget-api"
version = "0.1.0"

[dependencies]
actix = "*"
actix-web = "1.0.0-beta.5"
actix-service = "*"
actix-files = "0.1.0-beta.4"
actix-redis = { version = "0.5", default_features = false }
bytes = "0.4"
dotenv = "0.13"
env_logger = "0.6"
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
futures03 = { package = "futures-preview", version = "0.3.0-alpha.16", features = ["compat"] }
lazy_static = "1.1"
redis-async = "0.4"
serde = "1"
serde_derive = "1"
url = "1"
log = "0.4"

[dependencies.bigdecimal]
version = "0.0.14" # must match version of diesel dependency
features = ["serde"]

[dependencies.actix_web_async_compat]
git = "https://github.com/saks/actix_web_async_compat"

[dependencies.chrono]
features = ["serde"]
version = "*"

[dependencies.diesel]
features = ["numeric", "chrono", "postgres", "r2d2"]
version = "1.3"

[dependencies.djangohashers]
features = ["fpbkdf2"]
version = "1"

[dependencies.octo-budget-lib]
path = "../octo-budget-lib"

[dependencies.middlewares]
path = "../middlewares"

[dependencies.serde_json]
version = "1.0"
