[package]
name = "middlewares"
version = "0.1.0"
authors = ["Aliaksandr Rahalevich <saksmlz@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.2"
actix-service = "*"
actix-rt = "*"
futures = "0.3"
log = "0.4"
