[package]
name = "middlewares"
version = "0.1.0"
authors = ["Aliaksandr Rahalevich <saksmlz@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
actix-service = "0.4"
actix-files = "0.1"
futures = "0.1"
log = "0.4"
octo-budget-lib = { path = "../octo-budget-lib" }
