[package]
name = "middlewares"
version = "0.1.0"
authors = ["Aliaksandr Rahalevich <saksmlz@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-service = "*"
actix-rt = "1.0"
futures = "*"
log = "0.4"
