[package]
name = "middlewares"
version = "0.1.0"
authors = ["Aliaksandr Rahalevich <saksmlz@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0-beta.3"
actix-service = "*"
actix-files = "0.1.0-beta.4"
futures = "0.1"
log = "0.4"
