name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: pg-user
          POSTGRES_PASSWORD: pg-pass
          POSTGRES_DB: pg-db-name
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v1
    - name: install deps
      run: sudo apt-get -yqq install libpq-dev
    - name: Build
      run: cargo build --verbose
    - name: install diesel_cli
      run: cargo install diesel_cli --no-default-features --features postgres || echo "already installed"
    - name: setup test db
      env:
        DATABASE_URL: "postgres://pg-user:pg-pass@localhost:${{ job.services.postgres.ports[5432] }}/pg-db-name"
      run: diesel database setup
    - name: Run tests
      env:
        RUST_TEST_THREADS: 1
        DATABASE_URL: "postgres://pg-user:pg-pass@localhost:${{ job.services.postgres.ports[5432] }}/pg-db-name"
        REDIS_URL: "redis://localhost:${{ job.services.redis.ports[6379] }}"
      run: cargo test --verbose
