name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: $POSTGRES_DB
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379

    env:
      RUST_TEST_THREADS: 1
      DIESEL_CLI_VERSION: 1.4.0
      WASM_PACK_CLI_VERSION: 0.8.1
      POSTGRES_USER: pg-user
      POSTGRES_PASSWORD: pg-pass
      POSTGRES_DB: pg-db-name
      DATABASE_URL: "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:5432/$POSTGRES_DB"
      REDIS_URL: "redis://localhost:6379"

    steps:
    - uses: actions/checkout@v1

    - name: install deps
      run: sudo apt-get -yqq install libpq-dev

    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo check
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-check-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache dev tools
      uses: actions/cache@v1
      with:
        path: ext_bin
        key: ${{ runner.os }}-cargo-dev-tools-${{ env.DIESEL_CLI_VERSION }}-${{ env.WASM_PACK_CLI_VERSION }}

    - name: install ext CLIs
      run: make ext_cli

    - name: setup test db
      run: ./ext_bin/diesel database setup

    - name: check build
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all --bins --examples --tests

    - name: tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --all-features --no-fail-fast -- --nocapture

    - name: wasm tests
      run: cd ./octo-budget-frontend && ./../ext_bin/wasm-pack test --node
