name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: pg-user
          POSTGRES_PASSWORD: pg-pass
          POSTGRES_DB: pg-db-name
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379

    env:
      DIESEL_CLI_VERSION: 1.4.0

    steps:
    - uses: actions/checkout@v1
    - name: install deps
      run: sudo apt-get -yqq install libpq-dev
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache dev tools
      uses: actions/cache@v1
      with:
        path: ext_bin
        key: ${{ runner.os }}-cargo-index-${{ env.DIESEL_CLI_VERSION }}
    - name: debug cargo bin files
      run: ls -lah ~/.cargo/bin/
    - name: Build
      run: cargo build --verbose
    - name: install diesel_cli
      run: ./bin/install_diesel_cli.sh
    - name: setup test db
      env:
        DATABASE_URL: "postgres://pg-user:pg-pass@localhost:${{ job.services.postgres.ports[5432] }}/pg-db-name"
      run: diesel database setup
    - name: Run tests
      env:
        RUST_TEST_THREADS: 1
        DATABASE_URL: "postgres://pg-user:pg-pass@localhost:${{ job.services.postgres.ports[5432] }}/pg-db-name"
        REDIS_URL: "redis://localhost:${{ job.services.redis.ports[6379] }}"
      run: cargo test --verbose
